name: Deploy-preview

on:
    push:
        branches:
          - '*'
          - '!master'
          - '!main'

jobs:
  build-honkit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - uses: actions/setup-node@v3
      with:
        node-version: '22'

    - run: npm install -g honkit gitbook-plugin-include gitbook-plugin-toggle-chapters gitbook-plugin-git-author marked@v3.0.8

    - name: Build HonKit books
      run: .github/bin/buildHonkit.sh

    - uses: actions/upload-artifact@v3
      with:
        name: build-honkit
        path: build/

  build-gitbook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - uses: actions/setup-node@v1

    - run: npm install -g gitbook-cli marked@v3.0.8

    - name: Build GitBook books
      run: .github/bin/buildGitbook.sh

    - uses: actions/upload-artifact@v3
      with:
        name: build-gitbook
        path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: [build-honkit, build-gitbook]
    environment:
      name: 'staging'
      url: "https://preview.iiif.io/training/${{ github.ref_name}}/index.html"
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - uses: actions/download-artifact@v3
      with:
        name: build-honkit
        path: build/

    - uses: actions/download-artifact@v3
      with:
        name: build-gitbook
        path: build/

    - name: Convert index
      run: .github/bin/createIndex.sh

    - name: Update lastmod
      run: .github/bin/updateLastMod.sh

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::420715881449:role/GithubIdentify
        aws-region: us-east-1

    - name: Copy files to preview
      run: |
        aws s3 sync build/ s3://preview.iiif.io/training/${{ github.ref_name}} --acl 'public-read'