# This is a basic workflow to help you get started with Actions

name: Deploy-preview

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches:
          - '*'
          - '!master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: 'staging'
      url: "https://preview.iiif.io/training/`git rev-parse --abbrev-ref HEAD`/index.html"

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # store branch name in ${BRANCH_NAME}
    - name: Export BRANCH_NAME # store branch name in $BRANCH_NAME
      run: echo BRANCH_NAME=`git rev-parse --abbrev-ref HEAD` >> $GITHUB_ENV
    
    - uses: actions/setup-node@v1
    - run: npm install -g gitbook-cli marked@v3.0.8

    # Create the gitbooks in the build directory
    - name: Build gitbooks
      run: .github/bin/buildGitBooks.sh 

    - name: convert index  
      run: .github/bin/createIndex.sh

    - name: update lastmod
      run: .github/bin/updateLastMod.sh

    - name: Create GitHub deployment
      uses: bobheadxi/deployments@v0.4.1
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: staging

    # Deploy to 
   # - name: Configure AWS credentials from Test account
   #   uses: aws-actions/configure-aws-credentials@v1
   #   with:
   #     role-to-assume: arn:aws:iam::420715881449:role/GithubIdentify
   #     aws-region: us-east-1

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync build/ s3://preview.iiif.io/training/${BRANCH_NAME} --acl 'public-read' --dryrun


   # - name: Deploy to S3
   #   uses: jakejarvis/s3-sync-action@master
   #   with:
   #     args: --acl public-read 
   #   env:
   #     AWS_S3_BUCKET: "preview.iiif.io"
   #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   #     AWS_REGION: ${{ secrets.AWS_REGION }}
   #     SOURCE_DIR: "build/"
   #     DEST_DIR: "training/${BRANCH_NAME}"

   # - name: Update deployment status
   #   uses: bobheadxi/deployments@v0.4.1
   #   if: always()
   #   with:
   #     step: finish
   #     token: ${{ secrets.GITHUB_TOKEN }}
   #     status: ${{ job.status }}
   #     deployment_id: ${{ steps.deployment.outputs.deployment_id }}
   #     env_url: "https://preview.iiif.io/training/${{ env.BRANCH_NAME}}/index.html"

